# Generated by Django 5.2.17 on 2026-09-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_proformainvoice_last_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='pi_kind',
            field=models.CharField(blank=True, choices=[('battery', 'Battery'), ('ev_scooter', 'EV Scooter'), ('both', 'Both')], default='battery', max_length=20),
        ),
    ]
