# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_tax_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="tax_invoice_number",
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
