# Generated by Django 5.2.16 on 2026-09-29 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fill_employee_ids'),
        ('customers', '0002_customer_assigned_to_customer_party_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / MD'), ('sales', 'Sales Executive'), ('accountant', 'Accountant'), ('hr', 'HR'), ('manager', 'Manager'), ('technician', 'Technician'), ('dealer', 'Dealer Portal')], db_index=True, default='sales', max_length=20),
        ),
    ]
