# Generated by Django 5.2.17 on 2026-09-03 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Sales executive responsible for this dealer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='party_type',
            field=models.CharField(choices=[('dealer', 'Dealer'), ('vendor', 'Vendor')], db_index=True, default='dealer', max_length=20),
        ),
    ]
