# Generated by Django 5.2.17 on 2026-08-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='SPARS', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Manufacturing & Trading', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, default='Maharashtra', max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=80)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, max_length=15)),
                ('bank_branch', models.CharField(blank=True, max_length=150)),
                ('default_gst', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('pi_prefix', models.CharField(default='PI', max_length=10)),
                ('default_terms', models.TextField(blank=True, default='1. This is a Proforma Invoice and not a tax invoice.\n2. Payment to be made as per agreed terms.\n3. Goods once sold will not be taken back.\n4. Subject to jurisdiction of company registered office.\n5. Prices are exclusive of freight unless mentioned.')),
                ('email_template', models.TextField(blank=True, default='Dear {customer_name},\n\nPlease find attached Proforma Invoice {pi_number} dated {pi_date} for {grand_total}.\n\nValid till: {valid_till}\n\nThank you for your business.\n\nRegards,\n{company_name}')),
                ('whatsapp_template', models.TextField(blank=True, default='Hello {customer_name}, your Proforma Invoice {pi_number} dated {pi_date} for INR {grand_total} is ready. Valid till {valid_till}.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
            },
        ),
    ]
