# Generated by Django 5.2.17

from django.db import migrations, models


def seed_calendar(apps, schema_editor):
    CompanyEvent = apps.get_model("company", "CompanyEvent")
    if CompanyEvent.objects.exists():
        return
    from company.calendar_data import seed_calendar_events

    seed_calendar_events(CompanyEvent)


def unseed_calendar(apps, schema_editor):
    CompanyEvent = apps.get_model("company", "CompanyEvent")
    CompanyEvent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("event", "Company Event"),
                            ("birthday", "Birthday"),
                            ("festival", "Festival"),
                            ("holiday", "Holiday"),
                        ],
                        default="event",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.RunPython(seed_calendar, unseed_calendar),
    ]
