# Generated by Django 5.2.17

from django.db import migrations, models


def seed_public_content(apps, schema_editor):
    PublicPage = apps.get_model("company", "PublicPage")
    CareerOpening = apps.get_model("company", "CareerOpening")
    PublicPage.objects.get_or_create(pk=1)
    if CareerOpening.objects.exists():
        return
    CareerOpening.objects.bulk_create(
        [
            CareerOpening(
                title="Sales Executive",
                department="Sales",
                location="Noida",
                employment_type="Full-time",
                description="Dealer visits, quotations and follow-ups for EV scooters and battery packs across North India.",
                is_active=True,
                sort_order=1,
            ),
            CareerOpening(
                title="Accounts Executive",
                department="Accounts",
                location="Noida",
                employment_type="Full-time",
                description="GST-ready PIs, tax invoices, payment tracking and dealer ledger support.",
                is_active=True,
                sort_order=2,
            ),
            CareerOpening(
                title="Store & Dispatch Associate",
                department="Warehouse",
                location="Noida",
                employment_type="Full-time",
                description="Packing, stock checks and dispatch for lithium packs, LED batteries and scooter accessories.",
                is_active=True,
                sort_order=3,
            ),
        ]
    )


def unseed_public_content(apps, schema_editor):
    PublicPage = apps.get_model("company", "PublicPage")
    CareerOpening = apps.get_model("company", "CareerOpening")
    CareerOpening.objects.all().delete()
    PublicPage.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_companyevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hero_kicker",
                    models.CharField(
                        blank=True, default="National channel partner · SPARS Electric", max_length=200
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                (
                    "hero_body",
                    models.TextField(
                        blank=True,
                        default="EV scooters, lithium packs and LED batteries — quotations, tax invoices and dealer support from one Noida team.",
                    ),
                ),
                ("cta_primary", models.CharField(blank=True, default="Company calendar", max_length=80)),
                ("cta_secondary", models.CharField(blank=True, default="Contact HR / office", max_length=80)),
                (
                    "hero_image",
                    models.CharField(blank=True, default="/home/hero-showroom.jpg", max_length=400),
                ),
                ("about_kicker", models.CharField(blank=True, default="About the company", max_length=80)),
                (
                    "about_title",
                    models.CharField(
                        blank=True, default="A trading house built on people and products", max_length=200
                    ),
                ),
                (
                    "about_body",
                    models.TextField(
                        blank=True,
                        default="Kalpna Traders is the commercial face of SPARS Electric in North India. Dealers get GST-ready quotations, a live price list and a team that shows up for launches, birthdays and festivals alike.",
                    ),
                ),
                ("products_kicker", models.CharField(blank=True, default="Product range", max_length=80)),
                (
                    "products_title",
                    models.CharField(blank=True, default="What we quote every day", max_length=200),
                ),
                ("highlight_1_title", models.CharField(blank=True, default="EV Scooter", max_length=80)),
                (
                    "highlight_1_body",
                    models.TextField(
                        blank=True, default="Models, battery options and RTO-ready quotations from one desk."
                    ),
                ),
                (
                    "highlight_1_image",
                    models.CharField(blank=True, default="/home/ev-scooter.jpg", max_length=400),
                ),
                ("highlight_2_title", models.CharField(blank=True, default="Lithium packs", max_length=80)),
                (
                    "highlight_2_body",
                    models.TextField(
                        blank=True, default="Voltage, Ah, BMS and connector as per the signed specification."
                    ),
                ),
                (
                    "highlight_2_image",
                    models.CharField(blank=True, default="/home/lithium-battery.jpg", max_length=400),
                ),
                ("highlight_3_title", models.CharField(blank=True, default="LED / inverter", max_length=80)),
                (
                    "highlight_3_body",
                    models.TextField(
                        blank=True, default="Stock range with HSN, GST and dealer price list support."
                    ),
                ),
                (
                    "highlight_3_image",
                    models.CharField(blank=True, default="/home/led-battery.jpg", max_length=400),
                ),
                ("careers_kicker", models.CharField(blank=True, default="Careers", max_length=80)),
                (
                    "careers_title",
                    models.CharField(
                        blank=True, default="Build your career with Kalpna Traders", max_length=200
                    ),
                ),
                (
                    "careers_body",
                    models.TextField(
                        blank=True,
                        default="Sales, accounts and warehouse roles at our Noida desk. Apply with a short note — we reply from HR.",
                    ),
                ),
                ("careers_email", models.EmailField(blank=True, default="hrbp@kalpanatraders.com", max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Public page",
            },
        ),
        migrations.CreateModel(
            name="CareerOpening",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=80)),
                ("location", models.CharField(blank=True, default="Noida", max_length=120)),
                ("employment_type", models.CharField(blank=True, default="Full-time", max_length=40)),
                ("description", models.TextField(blank=True)),
                ("apply_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "-created_at", "id"],
            },
        ),
        migrations.RunPython(seed_public_content, unseed_public_content),
    ]
