# Generated by Django 5.2.17 on 2026-08-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('hsn_code', models.CharField(blank=True, max_length=8)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('G', 'Gram'), ('LTR', 'Litre'), ('MTR', 'Meter'), ('BOX', 'Box'), ('SET', 'Set'), ('NOS', 'Numbers'), ('PKT', 'Packet'), ('TON', 'Ton')], default='PCS', max_length=10)),
                ('gst', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
